title: <p align="center"> Florian Conti </p>
logo : /assets/img/profile_pic_Conti_Florian.png
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/florianconti/">LinkedIn</a> |
  <a href="https://github.com/Florianconti">GitHub</a>
  </p>
  
  <p align="justify">
  Récemment diplômé en Science des Données à la HEIG-VD, je suis passionné par l'analyse et la gestion des données
  <br><br>
  Au cours de ma formation, j'ai développé une expertise solide en gestion et transformation des données, modélisation statistique, ainsi qu'en apprentissage automatique. J'ai également acquis des compétences en conception d'architectures de données robustes et en création de pipelines de données optimisés.
  <br><br>
  </p>
#show_downloads : true
theme: jekyll-theme-minimal
